version: '3.8'
services:
  order-service:
    build: backend/services/order-service
    container_name: order-service
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      DY_TABLE_ORDERS: "ORDER-REGISTRATION"
      DY_TABLE_RECIPES: "AVAILABLE-RECIPES"

  kitchen-service:
    build: backend/services/kitchen-service
    container_name: kitchen-service
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      DY_TABLE_RECIPES: "AVAILABLE-RECIPES"
      TOTAL_RECIPES_NUMBER: 6
      INVENTORY_SERVICE_URL: "http://inventory-service:3003"
  
  inventory-service:
    build: backend/services/inventory-service
    container_name: inventory-service
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      FARMERS_MARKET_URL: "https://recruitment.alegra.com/api/farmers-market/buy"
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      DY_TABLE_ORDERS: "ORDER-REGISTRATION"
      DY_MARKET_REQUEST: "MARKET-REQUEST"
      AWS_URL_SQS_FIFO: https://sqs.us-east-1.amazonaws.com/545124311882/CONSULTING_MARKET.fifo
  
  frontend:
    build: frontend
    container_name: vue-frontend
    ports:
      - "8080:8080"
